# Copyright 2021 IBM Corp.
# SPDX-License-Identifier: Apache-2.0
# Pull Request Labeler Github Action Configuration: https://github.com/marketplace/actions/labeler

INFRA:
  - changed-files:
      - any-glob-to-any-file:
          - '.gitattributes'
          - '.gitignore'
          - '.github/**/*'

BUILD:
  - changed-files:
      - any-glob-to-any-file:
          - 'build/**/*'
          - 'project/**/*'

DOCS:
  - changed-files:
      - any-glob-to-any-file:
          - 'site/**/*'
          - '**/README.md'
          - '**/CONTRIBUTING.md'

EXAMPLES:
  - changed-files:
      - any-glob-to-any-file:
          - 'notebooks/**/*'

PYTHON:
  - changed-files:
      - any-glob-to-any-file:
          - 'python/**/*'

