# Copyright 2021 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

name: "build"

on:
  push:
    branches:
      - branch-spark-2.4
    paths-ignore:
      - '**/README.md'
      - '**/CONTRIBUTING.md'
      - 'site/**'
      - 'notebooks/**'
  pull_request:
    branches:
      - branch-spark-2.4
    paths-ignore:
      - '**/README.md'
      - '**/CONTRIBUTING.md'
      - 'site/**'
      - 'notebooks/**'
  workflow_dispatch:

jobs:
  build:
    name: Build xskipper and run Scala and Python tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Xskipper repository
        uses: actions/checkout@v2
      - name: Cache Coursier local repository
        uses: actions/cache@v2
        with:
          path: ~/.cache/coursier
          key: coursier-${{ hashFiles('**/pom.xml', '**/plugins.sbt') }}
          restore-keys: |
            coursier-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          architecture: x64
      - name: Install Python packages (Python 3.7)
        run: |
          python3.7 -m pip install pypandoc
          python3.7 -m pip install "pyspark==2.4.7"
      - name: Run sbt clean, Scala 2.11.8
        run: build/sbt ++2.11.8 clean
      - name: Run sbt compile, Scala 2.11.8
        run: build/sbt ++2.11.8 compile
      - name: Run Scala tests, Scala 2.11.8
        run: build/sbt ++2.11.8 test
      - name: Run Python tests
        run: python3.7 run-tests.py
