# Copyright 2021 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

name: "Publish Snapshot"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  publish-snapshot:
    if: github.repository == 'xskipper-io/xskipper'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch:
          - master
    steps:
      - name: Checkout Xskipper repository
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
      - name: Cache Maven local repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: snapshot-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            snapshot-maven-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish snapshot
        env:
          ASF_USERNAME: ${{ secrets.NEXUS_USER }}
          ASF_PASSWORD: ${{ secrets.NEXUS_PW }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          GIT_REF: ${{ matrix.branch }}
        run: |
          echo $PGP_SECRET | base64 --decode | gpg --batch --import
          sbt ++2.12.8 publishSigned